version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    build: ./kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  xampp:
    image: tomsik68/xampp
    ports:
      - "3306:3306"
    volumes:
      - ./xampp/sql:/docker-entrypoint-initdb.d

  logistics-service:
    build: ./logistics-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - xampp

  standard-delivery:
    build: ./standard-delivery
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  express-delivery:
    build: ./express-delivery
    ports:
      - "8082:8082"
    depends_on:
      - kafka

  international-delivery:
    build: ./international-delivery
    ports:
      - "8083:8083"
    depends_on:
      - kafka
